### ISSUE TITLE
[Feature] 백엔드 축제 사이트 공연 페이지 구현

### ISSUE THREAD

**Issue by sunwoo030616** [LikeLion-at-DGU/2024_fall_festival_back#16]
## ✔️ Issue
 가을 축제사이트 공연 페이지의 디테일 페이지와 축제의 열기 기능을 구현합니다.
 
## 📝 To-do
* [ ] 축제의 열기 기능 API 구현
* [ ] 공연 디테일 페이지 API 구현(메인곡, 공연정보, 인스타, 유튜브)
* [ ] API 테스트 및 디버깅
* [ ] 공연 관련 데이터 연동

 ## 🛠 Working time
 3d(~9/25)
