### ISSUE TITLE
[Feature] 백엔드 축제 사이트 부스 디테일 API 구현

### ISSUE THREAD

**Issue by chaehyeo-n** [LikeLion-at-DGU/2024_fall_festival_back#18]
## ✔️ Issue

가을 축제사이트 부스 디테일 모델과 API를 구현합니다.

## 📝 To-do

- [x] 부스 디테일 모델 생성
- [x] 부스 디테일 API 구현
- [x] API 테스트 및 디버깅

## 🛠 Working time

3d(~9/25)
