### ISSUE TITLE
[Feature] 백엔드 축제 사이트 부스목록 페이지 구현

### ISSUE THREAD

**Issue by ryann1203** [LikeLion-at-DGU/2024_fall_festival_back#19]
## ✔️ Issue
가을 축제 사이트의 부스 목록 페이지를 구현합니다.

## 📝 To-do
- [ ] 부스목록 모델 생성
- [ ] 부스 필터링 API 구현 (좋아요 수, 부스명, 운영 주체, 위치, 부스 이미지)
- [ ] API 테스트 및 디버깅

## 🛠 Working time
3days (~9/25)
