### ISSUE TITLE
[Feature] 백엔드 축제 사이트의 초기 환경 구축

### ISSUE THREAD

**Issue by lsoobin** [LikeLion-at-DGU/2024_fall_festival_back#9]
## ✔️ Issue

가을 축제사이트 백엔드의 초기 환경을 구축합니다.

## 📝 To-do

- [x]  가을 축제사이트 배포(aws)
- [x] 가을 축제사이트 스크린 걸기
- [x] 가을 축제사이트 CI/CD구현(민기)
- [x] API 명세서 검토 및 기본 세팅

## 🛠 Working time

3d(~9/23)
